backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "posts"
    label: "All Post"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "title", "commit_author"]
    format: "json"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - label: "Type"
        name: "type"
        default: "text"
        widget: "select"
        required: true
        options:
          - { label: "Text", value: "text" }
          - { label: "Online article", value: "article" }
          - { label: "Tweet", value: "tweet" }
          - { label: "Image", value: "image" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: false }
      - {
          label: "URL (should be required if Image or Link)",
          name: "url",
          widget: "string",
          required: false,
        }
      - {
          label: "Publish Date",
          name: "datetime",
          widget: "",
          required: true,
          dateFormat: true,
          timeFormat: true,
        }
      # - {
      #     label: "Body",
      #     name: "body",
      #     widget: "markdown",
      #     buttons:
      #       [
      #         "bold",
      #         "italic",
      #         "code",
      #         "link",
      #         "heading-one",
      #         "heading-two",
      #         "heading-three",
      #         "heading-four",
      #         "heading-five",
      #         "heading-six",
      #         "quote",
      #         "bulleted-list",
      #         "numbered-list",
      #       ],
      #     editorComponents: ["image"],
      #   }

  - name: "texts"
    label: "Texts"
    folder: "src/posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "title", "commit_author"]
    format: "json"
    filter: { field: "type", value: "text" }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - label: "Type"
        name: "type"
        default: "text"
        widget: "select"
        required: true
        options:
          - { label: "Text", value: "text" }
          - { label: "Online article", value: "article" }
          - { label: "Tweet", value: "tweet" }
          - { label: "Image", value: "image" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Summary",
          name: "summary",
          widget: "string",
          comment: "Depending on the type of post, this can be a link, or just text",
        }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: false }
      - {
          label: "URL (should be required if Image or Link)",
          name: "url",
          widget: "string",
          required: false,
        }

  - name: "articles"
    label: "Articles"
    folder: "src/posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "title", "commit_author"]
    format: "json"
    filter: { field: "type", value: "article" }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - label: "Type"
        name: "type"
        default: "article"
        widget: "select"
        required: true
        options:
          - { label: "Text", value: "text" }
          - { label: "Online article", value: "article" }
          - { label: "Tweet", value: "tweet" }
          - { label: "Image", value: "image" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Source", name: "source", widget: "string", required: true }
      - { label: "Public", name: "public", widget: "boolean", default: false }
      - {
          label: "URL (should be required if Image or Link)",
          name: "url",
          widget: "string",
          required: true,
        }

  - name: "tweets"
    label: "Tweets"
    folder: "src/posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "title", "commit_author"]
    format: "json"
    filter: { field: "type", value: "tweet" }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - label: "Type"
        name: "type"
        default: "tweet"
        widget: "select"
        required: true
        options:
          - { label: "Text", value: "text" }
          - { label: "Online article", value: "article" }
          - { label: "Tweet", value: "tweet" }
          - { label: "Image", value: "image" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: false }
      - {
          label: "URL (should be required if Image or Link)",
          name: "url",
          widget: "string",
          required: true,
        }

  - name: "images"
    label: "Images"
    folder: "src/posts"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    sortableFields: ["commit_date", "title", "commit_author"]
    format: "json"
    filter: { field: "type", value: "image" }
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - label: "Type"
        name: "type"
        default: "image"
        widget: "select"
        required: true
        options:
          - { label: "Text", value: "text" }
          - { label: "Online article", value: "article" }
          - { label: "Tweet", value: "tweet" }
          - { label: "Image", value: "image" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Source", name: "source", widget: "string", required: false }
      - { label: "Public", name: "public", widget: "boolean", default: false }
      - {
          label: "URL (should be required if Image or Link)",
          name: "url",
          widget: "string",
          required: true,
        }
